modulesrc/bc/Makefile.am
modulesrc/faults/Makefile.am
modulesrc/feassemble/Makefile.am
modulesrc/friction/Makefile.am
modulesrc/materials/Makefile.am
modulesrc/meshio/Makefile.am
modulesrc/mpi/Makefile.am
modulesrc/problems/Makefile.am
modulesrc/topology/Makefile.am
modulesrc/utils/Makefile.am

Add error message to Makefile if SWIG is disabled and SWIG generated files are not present.
Previously, the error message during "make" was that Make didn't know how to generate the SWIG generated files.

Improve error message when SWIG is needed but is not enabled

---

libsrc/pylith/topology/FieldBase.hh
libsrc/pylith/topology/FieldOps.cc

Disable reuse of discretizations via FieldBase:Discretization::operator== always returns false.
Can't reuse discretizations because they hold field (subfield) names and these get used in PETSc for solver settings.
If we want to avoid creating new discretizations, then we need to make a deep copy of the matching one and then set the field names in the copy.

Disable reuse of discretizations via operator==  always retrning false.

---

libsrc/pylith/topology/FieldQuery.cc
libsrc/pylith/utils/EventLogger.cc
libsrc/pylith/utils/EventLogger.hh
libsrc/pylith/utils/EventLogger.icc
tests/libtests/utils/TestEventLogger.cc
tests/libtests/utils/TestEventLogger.hh

Update EventLogger interface to rename getters/setters, i.e., setX() and getX().

Update EventLogger interface (rename getters/setters).

---

libsrc/pylith/materials/Query.cc
libsrc/pylith/topology/FieldQuery.cc
libsrc/pylith/topology/FieldQuery.hh

Converter function should return error message string not a `PetscErrorCode`, so that we can generate a more complete error message in the `FieldQuery` point query function.

Fix error trapping in FieldQuery point query for converter function

---

docker/pylith-testenv

Invoke PETSc configure with python2 to avoid configure failure if `which` isn't installed.

Fix docker build of PETSc when `which` isn't installed

---

libsrc/pylith/bc/NeumannTimeDependent.cc
libsrc/pylith/bc/NeumannTimeDependent.hh
libsrc/pylith/feassemble/IntegratorBoundary.cc
libsrc/pylith/feassemble/IntegratorBoundary.hh
libsrc/pylith/fekernels/NeumannTimeDependent.cc
modulesrc/bc/NeumannTimeDependent.i

Fix multiple bugs in using the Neumann BC with a time history.
1. Fix error in time history kernel. Amplitude is a vector; time history value is a scalar.
2. Fix updating auxiliary field with time history values. Need to open time history database and update add `IntegratorBoundary::prestep()`.

Fix Neumann BC with time history

---

libsrc/pylith/testing/MMSTest.cc

PETSc SNES finite-difference Jacobian test is run via a solve. Adjust TS 
and SNES settings so that the Jacobian is evaluated only once and there 
is no error when the solve fails. We have no expectation that the solve 
should converge.

Fix PETSc settings for MMS FD Jacobian test.

---

configure.ac
libsrc/pylith/testing/MMSTest.cc

Update PETSc requirement to 3.13.3.
Update MMSTest for changes to DMSNESCheckDiscretization().

Update to PETSc 3.13.3.

---

tests/fullscale/viscoelasticity/nofaults-3d/Makefile.am

The input files for the generalized Maxwell 3D full-scale test were not included in the Makefile.am.

Add missing test input files to Makefile for generalized 3D Maxwell full-scale test

---

libsrc/pylith/Makefile.am
libsrc/pylith/faults/FaultCohesiveKin.cc
libsrc/pylith/faults/KinSrc.cc
libsrc/pylith/faults/KinSrc.hh
libsrc/pylith/faults/KinSrcAuxiliaryFactory.cc
libsrc/pylith/faults/KinSrcAuxiliaryFactory.hh
libsrc/pylith/faults/KinSrcBrune.cc
libsrc/pylith/faults/KinSrcBrune.hh
libsrc/pylith/faults/KinSrcConstRate.cc
libsrc/pylith/faults/KinSrcLiuCos.cc
libsrc/pylith/faults/KinSrcLiuCos.hh
libsrc/pylith/faults/KinSrcStep.cc
libsrc/pylith/faults/KinSrcStep.hh
libsrc/pylith/faults/KinSrcTimeHistory.cc
libsrc/pylith/faults/KinSrcTimeHistory.hh
libsrc/pylith/faults/Makefile.am
libsrc/pylith/faults/faultsfwd.hh
modulesrc/faults/KinSrc.i
modulesrc/faults/KinSrcBrune.i
modulesrc/faults/KinSrcConstRate.i
modulesrc/faults/KinSrcLiuCos.i
modulesrc/faults/KinSrcStep.i
modulesrc/faults/KinSrcTimeHistory.i
modulesrc/faults/Makefile.am
modulesrc/faults/faults.i
pylith/Makefile.am
pylith/faults/KinSrcBrune.py
pylith/faults/KinSrcLiuCos.py
pylith/faults/KinSrcTimeHistory.py

Add slip time functions used primarily in dynamic simulations:
* Integral of Brune's far-field time function
* Liu cosine-sine slip time function
* Time history from data file slip time function
Closes https://github.com/geodynamics/pylith/issues/170

Add Brune, Liu, and time history slip time functions.

---

pylith/meshio/MeshIOAscii.py
pylith/meshio/MeshIOCubit.py
pylith/meshio/MeshIOLagrit.py

Trap missing mesh files earlier by checking that files exist during configure (Pyre validators).

Verify existence of mesh input files in Pyre validators.

---

libsrc/pylith/faults/FaultCohesiveKin.cc
libsrc/pylith/faults/FaultCohesiveKin.hh
libsrc/pylith/faults/KinSrc.cc
libsrc/pylith/faults/KinSrc.hh
libsrc/pylith/faults/KinSrcBrune.cc
libsrc/pylith/faults/KinSrcConstRate.cc
libsrc/pylith/faults/KinSrcLiuCos.cc
libsrc/pylith/faults/KinSrcStep.cc
libsrc/pylith/faults/KinSrcTimeHistory.cc
libsrc/pylith/faults/KinSrcTimeHistory.hh
libsrc/pylith/topology/VisitorMesh.icc
modulesrc/faults/KinSrc.i
modulesrc/faults/KinSrcTimeHistory.i

Fix kludge in `FaultCohesiveKin`.
Set slip subfield in fault auxiliary field for earthquake ruptures. Store cumulative slip in local PETSc vector and then insert slip into fault auxiliary field. Use two PETSc vectors: one for storing the slip for a given rupture and one for accumulating the total slip across all ruptures at the current time.

Robust implementation for updating slip in fault auxiliary field

---

libsrc/pylith/feassemble/Integrator.cc
libsrc/pylith/feassemble/Integrator.hh
libsrc/pylith/materials/Elasticity.cc
libsrc/pylith/materials/RheologyElasticity.cc
libsrc/pylith/materials/RheologyElasticity.hh

Add data member to `RheologyElasticity` so bulk rheologies can specify when the Jacobian with elastic constants needs to be recomputed.
Elastic rheologies should set the `_rhsJacobianTriggers` data member in their constructor. The default is `NEW_JACOBIAN_NEVER` which means the Jacobian is constant (doesn't change after it has been computed).

Add missing code so elastic rheologies can specify when Jacobian should be recomputed

---

pylith/tests/FullTestApp.py

Fix bug in checking of tolerance type in `FullTestApp`.
The tolerance is either a `float` or `dict`, never a `map` (which was what the type check was comparing against).
Fixing this leads to test failures for the Terzaghi and Mandel poroelasticity full-scale tests.

Fix bug in checking of tolerance type (could be dict, never a map)

---

libsrc/pylith/faults/TopologyOps.cc
libsrc/pylith/feassemble/IntegratorDomain.cc
libsrc/pylith/feassemble/IntegratorInterface.cc
libsrc/pylith/materials/Elasticity.cc
libsrc/pylith/materials/IncompressibleElasticity.cc
libsrc/pylith/materials/Material.cc
libsrc/pylith/materials/Poroelasticity.cc
libsrc/pylith/meshio/MeshIO.cc
libsrc/pylith/problems/InitialConditionPatch.cc
libsrc/pylith/topology/Mesh.cc
libsrc/pylith/topology/Mesh.hh
libsrc/pylith/topology/MeshOps.cc
libsrc/pylith/topology/RefineUniform.cc
libsrc/pylith/topology/ReverseCuthillMcKee.cc

There are a few places where we rely on a label over all of the cells, including hybrid cells. The name given by Mesh::getCellsLabelName() serves this purpose. It is also useful in the integration over domain cells.

Replace hardwired 'material-id' name with value given by pylith::topology::Mesh::getCellsLabelName()

---

libsrc/pylith/testing/TestDriver.cc
libsrc/pylith/testing/TestDriver.hh

Use `--petsc ARG=VALUE` to pass command line argument `ARG` with value `VALUE` to PETSc. `=VALUE` can be omitted.
Only pass `argv[0]` to `PetscInitialize()` to avoid warnings about unprocessed arguments unrelated to PETSc.
Closes #255

Create command line option for passing arguments to PETSc.

---

configure.ac
libsrc/pylith/faults/KinSrc.cc
libsrc/pylith/feassemble/ConstraintSimple.cc
libsrc/pylith/feassemble/ConstraintSpatialDB.cc
libsrc/pylith/feassemble/ConstraintUserFn.cc
libsrc/pylith/feassemble/IntegratorBoundary.cc
libsrc/pylith/feassemble/IntegratorDomain.cc
libsrc/pylith/feassemble/IntegratorInterface.cc
libsrc/pylith/problems/TimeDependent.cc
libsrc/pylith/testing/MMSTest.cc
tests/libtests/topology/TestFieldMesh.cc

* Need to use `PetscWeakForm` for boundary integration.
* Use `DMSetAuxiliaryVector()` instead of `PetscObjectCompose()` to set auxiliary vector in integration and projection.
For now, PETSc uses (label=NULL, labelValue=0) when getting the auxiliary vector from the PetscDM, so we must do the same when setting the auxiliary vector. Later, PETSc will use the label and label value.
Closes #260

Updates for changes to PETSc boundary integration API and setting auxiliary vector

---

libsrc/pylith/feassemble/IntegratorDomain.cc

Added PetscReal t to the external definition for DMPlexComputeResidual_Internal in IntegratorDomain.cc. Fixes passing of nonsense time values to kernels during tests.

Added PetscReal t to definition of DMPlexComputeResidual_Internal

---

docker/pylith-testenv
libsrc/pylith/feassemble/Integrator.hh
libsrc/pylith/feassemble/IntegratorBoundary.cc
libsrc/pylith/feassemble/IntegratorDomain.cc
libsrc/pylith/feassemble/IntegratorInterface.cc
libsrc/pylith/meshio/MeshBuilder.cc
libsrc/pylith/topology/FieldQuery.cc
tests/libtests/meshio/TestMeshIO.cc
tests/libtests/topology/TestFieldMesh.cc
tests/mmstests/elasticity/Makefile.am
tests/mmstests/elasticity/TestIsotropicLinearElasticity2D_UniformStrain.cc

* Updates for changes to PETSc weak form key (add integration part).
* Add distorted quad mesh to MMS elasticity test.
* A couple small fixes for simple memory errors.
Closes #285
Closes #274

Updates for using weak form key with integration part. Some small code clean up.

---

libsrc/pylith/bc/AbsorbingDampers.cc
libsrc/pylith/bc/DirichletTimeDependent.cc
libsrc/pylith/bc/DirichletUserFn.cc
libsrc/pylith/bc/DirichletUserFn.hh
libsrc/pylith/bc/NeumannTimeDependent.cc
libsrc/pylith/faults/FaultCohesiveKin.cc
libsrc/pylith/faults/KinSrc.cc
libsrc/pylith/feassemble/ConstraintUserFn.cc
libsrc/pylith/materials/Elasticity.cc
libsrc/pylith/materials/IncompressibleElasticity.cc
libsrc/pylith/materials/Poroelasticity.cc
libsrc/pylith/meshio/OutputSolnPoints.cc
libsrc/pylith/problems/TimeDependent.cc
libsrc/pylith/testing/MMSTest.cc
libsrc/pylith/testing/MMSTest.hh
libsrc/pylith/topology/Field.cc
libsrc/pylith/topology/Field.hh
tests/libtests/bc/TestAbsorbingDampers.cc
tests/libtests/bc/TestNeumannTimeDependent.cc
tests/libtests/feassemble/TestAuxiliaryFactory.cc
tests/libtests/meshio/TestOutputSolnPoints.cc

Add time derivative of field (fnDot) to DirichletUserFn. We already have the time derivative in ConstraintUserFn. These are needed for time dependent MMS tests.

Add time derivative of field to DirichletUserFn

---

libsrc/pylith/meshio/OutputSoln.cc
libsrc/pylith/meshio/OutputSoln.hh
libsrc/pylith/meshio/OutputSolnBoundary.cc
libsrc/pylith/meshio/OutputSolnPoints.cc

Fix memory error associated with attempt to write Lagrange multiplier field over the boundary (or points) when writing solution fields. Use `FieldOps::getSubfieldNamesDomain()` to limit fields to only those over the domain (as was being doing for `OutputSolnDomain`.

Limit boundary and point solution output to only fields over domain.

---

libsrc/pylith/feassemble/IntegratorBoundary.cc
tests/fullscale/linearelasticity/nofaults-2d/TestGravityIncompressible.py
tests/fullscale/linearelasticity/nofaults-3d/TestGravity.py
tests/fullscale/linearelasticity/nofaults-3d/TestGravityIncompressible.py

* Updates for changes to PETSc boundary integration interface (now uses key).
* Small fixes to gravity examples (vertex fields -> cell fields; boundary solution).

Update PETSc interface for boundary integration (now uses key)

---

docs-sphinx/developer/contributing/codingstyle.md

This fixed a typo in codingstyle.md where PetscFinalize is now in single quotes.  
My editor also detected spaces at the end of lines and deleted this as well.

demo to fix coding style for petscfinalize

---

docs-sphinx/developer/testing/fullscale.md
docs-sphinx/developer/testing/index.md
docs-sphinx/developer/testing/libtests.md
docs-sphinx/developer/testing/mmstests.md

Fixes miscellaneous typos and omitted commas in the sphinx developer documentation Testing section.

Fix typos and grammar inDeveloper Doc -Testing

---

docs-sphinx/developer/contributing/codelayout.md
docs-sphinx/developer/contributing/newmaterial.md
docs-sphinx/developer/contributing/petscfem.md
docs-sphinx/developer/contributing/rebuilding.md
docs-sphinx/developer/contributing/workflow.md

Small changes like adding missing punctuation and deleting redundant words, and a couple of formatting errors. There is one reference to "coding-style.md" that I changed to "codingstyle.md" since that is the name of the file as it appears in the developer/contributing directory.

Editing typos in the developer/contributing documentation

---

docs-sphinx/user/index.md
docs-sphinx/user/preface.md

Hyperlinks are long form now (couldn't get them to work as written); the version number macro did not carry over either so as of now version numbers have to be updated manually until issue is resolved.

Added preface.md

---

configure.ac
tests/libtests/meshio/data/hex8_cell_t10.vtk
tests/libtests/meshio/data/hex8_mat_cell_t10.vtk
tests/libtests/meshio/data/hex8_mat_vertex_t10.vtk
tests/libtests/meshio/data/hex8_points_vertex_t10.vtk
tests/libtests/meshio/data/hex8_surf_cell_t10.vtk
tests/libtests/meshio/data/hex8_surf_vertex_t10.vtk
tests/libtests/meshio/data/hex8_vertex_t10.vtk
tests/libtests/meshio/data/quad4_cell_t10.vtk
tests/libtests/meshio/data/quad4_mat_cell_t10.vtk
tests/libtests/meshio/data/quad4_mat_vertex_t10.vtk
tests/libtests/meshio/data/quad4_points_vertex_t10.vtk
tests/libtests/meshio/data/quad4_surf_cell_t10.vtk
tests/libtests/meshio/data/quad4_surf_vertex_t10.vtk
tests/libtests/meshio/data/quad4_vertex_t10.vtk
tests/libtests/meshio/data/tet4_cell_t10.vtk
tests/libtests/meshio/data/tet4_mat_cell_t10.vtk
tests/libtests/meshio/data/tet4_mat_vertex_t10.vtk
tests/libtests/meshio/data/tet4_points_vertex_t10.vtk
tests/libtests/meshio/data/tet4_surf_cell_t10.vtk
tests/libtests/meshio/data/tet4_surf_vertex_t10.vtk
tests/libtests/meshio/data/tet4_vertex_t10.vtk
tests/libtests/meshio/data/tri3_cell_t10.vtk
tests/libtests/meshio/data/tri3_mat_cell_t10.vtk
tests/libtests/meshio/data/tri3_mat_vertex_t10.vtk
tests/libtests/meshio/data/tri3_points_vertex_t10.vtk
tests/libtests/meshio/data/tri3_surf_cell_t10.vtk
tests/libtests/meshio/data/tri3_surf_vertex_t10.vtk
tests/libtests/meshio/data/tri3_vertex_t10.vtk

Update VTK output test files to account for better naming of "domain" in PETSc VTK output.

Update to use PETSc 3.15.4

---

libsrc/pylith/testing/MMSTest.cc
libsrc/pylith/testing/TestDriver.cc

* Fix setting PETSc checkstack option.
* Add missing help info for journals.
Use of command line arguments with TestDriver allows activating specific journals and tests. We no longer need to deactivate the MMSTest journal at the end of every test.
Closes #281

Fix a few issues with TestDriver

---

configure.ac
libsrc/pylith/fekernels/FaultCohesiveKin.cc
tests/mmstests/Makefile.am

* Update to PETSc 3.16.1
* Update PETSc `knepley/pylith` branch to allow multiple hybrid fields.
* Fix fault Jacobian integration (indexing of result)

Fix fault Jacobian integration

---

docs-sphinx/user/governingeqns/elasticity-infstrain/dynamic.md
docs-sphinx/user/governingeqns/elasticity-infstrain/index.md
docs-sphinx/user/governingeqns/elasticity-infstrain/quasistatic.md
docs-sphinx/user/governingeqns/index.md

Coming back to this after a few weeks focusing on other things, so apologies if its a little disoriented. 
My understanding from the formatting you set in your pull request is that you'd like to use \begin{equation} or \begin{gather} for 'unlabeled' equations, and ```{math} for 'labeled' equations, correct?
The next section (3.4) has the same structure (index - quasistatic - dynamic) but the 'dynamic' section is far longer so I lean toward keeping these sections (3.3 and 3.4) split into different files. Should I consolidate, or keep this as is and structure 3.4 the same way?

Governingeqns elasticity infstrain

---

docs-sphinx/quickref.md
docs-sphinx/user/governingeqns/elasticity-infstrain-prescribedslip/dynamic.md
docs-sphinx/user/governingeqns/elasticity-infstrain-prescribedslip/index.md
docs-sphinx/user/governingeqns/elasticity-infstrain-prescribedslip/quasistatic.md
docs-sphinx/user/governingeqns/index.md

Seems like the environment "multlined" isn't recognized. I've used \dots in specific cases to clarify equations which continue onto another line. Is there a different way you'd like this handled?

Elasticity infstrain prescribedslip

---

configure.ac
libsrc/pylith/fekernels/FaultCohesiveKin.cc
libsrc/pylith/topology/FieldOps.cc

Updates associated with updating PETSc to 3.16.5.
`knepley/pylith` updated to PETSc 3.16.5 (with a few additional bug fixes):
* Fixes for downloading ML.
* Fix for VTK output on submesh in a domain with a fault.

Update PETSc to 3.16.5.

---

docs/user/examples/reverse-2d/step05-onefault.md
docs/user/examples/reverse-2d/step06-twofaults-elastic.md
docs/user/examples/strikeslip-2d/step01-slip.md
docs/user/examples/strikeslip-2d/step02-slip-velbc.md
docs/user/examples/strikeslip-2d/step03-multislip-velbc.md
docs/user/examples/strikeslip-2d/step04-varslip.md
docs/user/examples/strikeslip-2d/step05-greensfns.md
docs/user/run-pylith/petsc-options.md
examples/reverse-2d/step06_twofaults_elastic.cfg
examples/reverse-2d/step07_twofaults_maxwell.cfg
examples/reverse-2d/step08_twofaults_powerlaw.cfg
examples/strikeslip-2d/pylithapp.cfg
libsrc/pylith/materials/Elasticity.cc
libsrc/pylith/materials/Poroelasticity.cc
tests/fullscale/linearelasticity/faults-2d/threeblocks.cfg
tests/mmstests/faults/TestFaultKin2D_OneFaultShearNoSlip.cc
tests/mmstests/faults/TestFaultKin2D_ThreeBlocksStatic.cc
tests/mmstests/faults/TestFaultKin2D_TwoBlocksStatic.cc
tests/mmstests/faults/TestFaultKin2D_TwoFaultsShearNoSlip.cc

* Use LU instead of ILU for better performance.
* Update tests and examples with null space to use ILU by setting PETSc option directly.

Update default solver settings for elasticity and poroelasticity

---

docs/developer/contributing/documentation/quickref.md
docs/user/appendices/analytical-solns.md
docs/user/examples/paraview-python.md
docs/user/glossary/index.md
docs/user/governingeqns/elasticity-infstrain-prescribedslip/dynamic.md
docs/user/governingeqns/elasticity-infstrain-prescribedslip/index.md
docs/user/governingeqns/elasticity-infstrain/bulk-rheologies/effective-stress.md
docs/user/governingeqns/elasticity-infstrain/bulk-rheologies/elasticity-constitutive.md
docs/user/governingeqns/elasticity-infstrain/bulk-rheologies/linear-elastic.md
docs/user/governingeqns/elasticity-infstrain/bulk-rheologies/powerlaw.md
docs/user/governingeqns/elasticity-infstrain/quasistatic.md
docs/user/governingeqns/incompressible-elasticity.md
docs/user/governingeqns/petsc-formulation.md
docs/user/install/index.md
docs/user/physics/faults/index.md
libsrc/pylith/materials/IncompressibleElasticity.cc

* Fix LaTeX build for documentation. Biggest error was incorrect nested match environments (Sphinx html generator didn't care, but LaTeX did; align -> aligned; gather -> gathered).
* Improve instructions for how to use ParaView Python scripts when starting ParaView with a shortcut.
* Add instructions for how to remove macOS quarantine attributes when downloading the tarball.

Fix LaTeX build of documenation. Small enhancements

---

configure.ac
libsrc/pylith/feassemble/ConstraintSimple.cc
libsrc/pylith/topology/Field.cc

* Updates to PETSc to resolve PetscSF bugs
* Update to `ConstraintSimple` for more flexibility in finding DS to set constraint
* Update to PETSc 3.17.4
Closes #518 #519

FIX: Resolve bugs associated with running in parallel with faults

---

libsrc/pylith/problems/GreensFns.cc
libsrc/pylith/problems/Problem.cc
libsrc/pylith/problems/TimeDependent.cc

Use names of scalars and fields provided by IntegrationData static data members. Incorrect values are detected at compile time rather than runtime or not at all.
Fixes dynamic simulations without faults.

FIX: Fix dynamic simulations (no faults)

---

applications/pylith_powerlaw_gendb
configure.ac
examples/meshing-cubit/cellsize/exodus_add_properties.py
examples/subduction-3d/utils/generate_initial_stress.py
examples/subduction-3d/utils/make_synthetic_gpsdisp.py
examples/subduction-3d/utils/slip_invert.py
libsrc/pylith/Makefile.am
playpen/viscorestart/gen_dp3d_statedb.py
playpen/viscorestart/gen_dpps_statedb.py
playpen/viscorestart/gen_genmax3d_statedb.py
playpen/viscorestart/gen_genmaxps_statedb.py
playpen/viscorestart/gen_max3d_statedb.py
playpen/viscorestart/gen_maxps_statedb.py
playpen/viscorestart/gen_powerlaw3d_statedb.py
playpen/viscorestart/gen_powerlawps_statedb.py
pylith/apps/EqInfoApp.py
pylith/bc/DirichletTimeDependent.py
pylith/faults/FaultCohesiveImpulses.py
pylith/testing/FullTestApp.py
tests/fullscale/eqinfo/generate.py

* numpy v1.24 removes numpy.int; replace use of numpy.int with numpy.intc or numpy.int64.
* Require numpy v1.20.0 or later
* Small fix for using Python framework (binary from python.org) on macOS.

Update for using numpy.1.24; require numpy.1.20 or later

---

libsrc/pylith/materials/Elasticity.cc

Kernels were only being set for DYNAMIC_IMEX, so no lumped Jacobian was being computed (equivalent to using identity).

FIX: Need to set Jacobian kernels for lumped mass matrix for dynamic.

---

libsrc/pylith/fekernels/IsotropicLinearMaxwell.hh

The constant dt was not being set for refState version.

Set dt in IsotropicLinearMaxwell::setContext_refState

---

libsrc/pylith/faults/FaultCohesive.hh
libsrc/pylith/faults/FaultCohesiveImpulses.cc
libsrc/pylith/faults/FaultCohesiveImpulses.hh
libsrc/pylith/faults/FaultCohesiveKin.cc
libsrc/pylith/faults/FaultCohesiveKin.hh
tests/mmstests/incompressibleelasticity/nofaults-2d/TestIncompressibleElasticity.hh
tests/src/FaultCohesiveStub.cc

`createIntegrator()` is implemented in `FaultCohesive` with identical implementation in `FaultCohesiveKin` and `FaultCohesiveImpulses`. There is no reason for this duplicate code and we can just use the implementation in `FaultCohesive`.

FIX: Remove createIntegrator() from classes derived from FaultCohesive

---

configure.ac
libsrc/pylith/meshio/DataWriter.cc
libsrc/pylith/meshio/DataWriter.hh
libsrc/pylith/meshio/DataWriterHDF5.cc
libsrc/pylith/meshio/DataWriterHDF5Ext.cc
tests/mmstests/linearelasticity/faults-2d/ThreeBlocksStatic.cc

- Update to PETSc 3.19.5.
- Use `VecView()` instead of private `VecView_Seq()` and `VecView_MPI()`.
- Allow zero residual in MMS test with rigid block motion.

Update PETSc to 3.19.5

---

libsrc/pylith/fekernels/Poroelasticity.hh

Bulk density kernel for derived field would return garbage values due setting pointer for return value instead of setting value associated with pointer.

FIX: Correct setting return value in kernel for bulk density derived field

---

pylith/materials/AuxSubfieldsIsotropicLinearPoroelasticity.py

Reference stress and strain were missing from the pool of subfields (used to set discretization information) for IsotropicLinearPoroelasticity.
Fixes #652

FIX: Add reference stress and strain to pool of IsotropicLinearPoroelasticity auxiliary subfields

---

docs/references.bib
docs/user/governingeqns/poroelasticity/dynamic.md
docs/user/governingeqns/poroelasticity/index.md

This PR adds/updates the formulation for poroelastodynamics base on this [paper](https://asmedigitalcollection.asme.org/appliedmechanics/article-abstract/80/6/061021/370399/Fundamental-Solutions-of-Poroelastodynamics-in?redirectedFrom=fulltext).

Poroelastodynamic ref and formulation

---

docs/intro/preface.md

Corrects a few typos.  
This also supports the previous pull request #674 in adding "a" and "b" to the year 2023 in the citations.

Correct a few typos

---

CHANGES.md
configure.ac
docs/conf.py
pylith/__init__.py
setup.cfg

- Update m4 macros for compatibility with numpy v2
- Set version to 4.2.0dev

Update m4 macros (numpy v2 compatibility)

---

CHANGES.md
libsrc/pylith/materials/AuxiliaryFactoryElastic.cc
libsrc/pylith/materials/AuxiliaryFactoryElasticity.cc
libsrc/pylith/materials/AuxiliaryFactoryPoroelastic.cc
libsrc/pylith/materials/AuxiliaryFactoryPoroelasticity.cc
libsrc/pylith/materials/AuxiliaryFactoryPoroelasticity.hh
libsrc/pylith/materials/AuxiliaryFactoryViscoelastic.cc
libsrc/pylith/materials/Query.cc
libsrc/pylith/topology/FieldBase.hh
libsrc/pylith/topology/FieldQuery.cc
libsrc/pylith/topology/FieldQuery.hh
tests/libtests/materials/TestAuxiliaryFactoryElasticity.cc
tests/libtests/materials/TestAuxiliaryFactoryElasticity_Cases.cc
tests/libtests/materials/TestAuxiliaryFactoryLinearElastic.cc
tests/libtests/materials/TestAuxiliaryFactoryLinearElastic_Cases.cc
tests/libtests/topology/TestFieldQuery.cc
tests/src/FieldTester.cc

Closes #779
We still need to adjust auxiliary fields to make better use of this feature (will affect parameter files so delaying those changes to v5.0). Refer to #790.

Add ability to check scale of material properties when getting values from spatial databases

---

libsrc/pylith/faults/KinSrcRamp.cc
tests/fullscale/linearelasticity/faults-2d/shearnoslip.cfg

FIX: Avoid divide by zero in KinSrcRamp slip time function (zero slip or impulse duration).
