geodynamics/pylith

- applications/pylith.in
Trap import errors in PyLith application driver and provide diagnostic information.
> Trap import errors in application driver and provide diagnostic information

- pylith/utils/DumpParameters.py
- pylith/utils/PetscManager.py
Treat `PetscManager` as special case in order to dump PETSc options (to JSON file).
> Add dumping of PETSc options

- libsrc/pylith/problems/Problem.cc
- tests/mmstests/faults/TestFaultKin.cc
Fix small bug in setting kinematic rupture in fault MMS test.
> Fix small bug in setting up fault MMS test

- examples/3d/subduction/mesh/coordsys.py
- examples/3d/subduction/mesh/generate_surfjou.py
Update examples/3d/subduction mesh generation for changes to spatialdata API (Proj 6.x).
> Examples: 3d/subduction - update mesh generation for spatialdata API changes

- pylith/tests/UnitTestApp.py
Fix indentation error in UnitTestApp associated with code coverage.
> Fix indentation error in UnitTestApp.py.

- libsrc/pylith/bc/DirichletTimeDependent.cc
- libsrc/pylith/bc/TimeDependentAuxiliaryFactory.cc
- libsrc/pylith/feassemble/ConstraintSpatialDB.cc
- libsrc/pylith/fekernels/TimeDependentFn.cc
- pylith/bc/DirichletTimeDependent.py
Several small bugs in initializing Dirichlet BC with a user time 
history.
> Fix Dirichlet BC with time history.

- .travis.yml
- tests/fullscale/viscoelasticity/nofaults-2d/pylithapp.cfg
- tests/fullscale/viscoelasticity/nofaults-3d/pylithapp.cfg
Switch from `lu` to `ml` preconditioner for viscoelastic full-scale tests.
> Update preconditioner for viscoelastic full-scale tests

- libsrc/pylith/meshio/MeshIO.cc
- libsrc/pylith/topology/Mesh.icc
- libsrc/pylith/topology/MeshOps.cc
- tests/libtests/topology/TestFieldMesh.cc
- tests/libtests/topology/TestFieldQuery_Cases.cc
> Improve error message for bounding box check. Add check of length scale against nondimensional cell size.

- tests/mmstests/elasticity/Makefile.am
- tests/mmstests/elasticity/TestIsotropicLinearElasticity3D_BodyForce.cc
- tests/mmstests/elasticity/TestIsotropicLinearElasticity3D_Gravity.cc
- tests/mmstests/elasticity/TestIsotropicLinearElasticity3D_GravityRefState.cc
- tests/mmstests/elasticity/TestIsotropicLinearElasticity3D_UniformStrain.cc
> Added 3D isotropic linear elasticity MMS tests

- libsrc/pylith/materials/Elasticity.cc
- libsrc/pylith/materials/IncompressibleElasticity.cc
Replace multiple `if` statements and duplicate code with use of bits and `switch` statement in setting RHS residual kernels for Elasticity and IncompressibleElasticity.
Code is now consistent with how time-dependent boundary condition kernels and Poroelasticity residual kernels are set. 
Closes #221
> Cleanup setting RHS residual kernels for Elasticity and IncompressibleElasticity

- libsrc/pylith/faults/FaultCohesiveKin.cc
- libsrc/pylith/faults/TopologyOps.cc
- libsrc/pylith/faults/TopologyOps.hh
- libsrc/pylith/feassemble/Integrator.cc
- libsrc/pylith/feassemble/Integrator.hh
- libsrc/pylith/feassemble/IntegratorBoundary.cc
- libsrc/pylith/feassemble/IntegratorBoundary.hh
- libsrc/pylith/feassemble/IntegratorDomain.cc
- libsrc/pylith/feassemble/IntegratorDomain.hh
- libsrc/pylith/feassemble/IntegratorInterface.cc
- libsrc/pylith/feassemble/IntegratorInterface.hh
- libsrc/pylith/materials/Elasticity.cc
- libsrc/pylith/materials/IncompressibleElasticity.cc
- libsrc/pylith/materials/Poroelasticity.cc
- tests/libtests/feassemble/TestIntegratorDomain.cc
Also replace use of `DMLabelGetStratumBounds()` with `DMGetStratumIS()`.
Closes #233 
Closes #85
> Add label name and value of associated integrator domain to Integrator

- libsrc/pylith/feassemble/IntegratorDomain.cc
- libsrc/pylith/feassemble/IntegratorInterface.cc
Fix memory leaks introduced in PR #235
> Fix integrator memory leak

- doc/userguide/governingeqns/poroelasticity.tex
Updated poroelastic formulation documentation.
> Modified poroelastic formulation doc

- pylith/materials/RheologyElasticity.py
- pylith/materials/RheologyIncompressibleElasticity.py
- pylith/materials/RheologyPoroelasticity.py
- pylith/meshio/OutputObserver.py
- pylith/problems/Physics.py
- pylith/problems/Solution.py
- tests/fullscale/linearelasticity/nofaults-2d/pylithapp.cfg
- tests/fullscale/poroelasticity/mandel/mandel.cfg
- tests/fullscale/poroelasticity/terzaghi/terzaghi.cfg
Use the Pyre locator to determine if a local value is not the default and should override the problem default.
Closes #226
> Fix detection of whether to override problem defaults

- libsrc/pylith/faults/FaultCohesive.cc
- libsrc/pylith/testing/TestDriver.cc
- libsrc/pylith/testing/TestDriver.hh
- tests/libtests/materials/TestAuxiliaryFactoryElastic.cc
- tests/libtests/materials/TestIsotropicLinearElasticity3D.cc
- tests/libtests/materials/TestIsotropicLinearElasticityPlaneStrain.cc
- tests/libtests/materials/TestIsotropicLinearGenMaxwell3D.cc
- tests/libtests/materials/TestIsotropicLinearGenMaxwellPlaneStrain.cc
- tests/libtests/materials/TestIsotropicLinearMaxwell3D.cc
- tests/libtests/materials/TestIsotropicLinearMaxwellPlaneStrain.cc
- tests/libtests/meshio/TestMeshIOAscii.cc
- tests/libtests/meshio/TestMeshIOCubit.cc
- tests/libtests/meshio/TestMeshIOLagrit.cc
- tests/mmstests/elasticity/TestIsotropicLinearElasticity2D_BodyForce.cc
- tests/mmstests/elasticity/TestIsotropicLinearElasticity2D_Gravity.cc
- tests/mmstests/elasticity/TestIsotropicLinearElasticity2D_GravityRefState.cc
- tests/mmstests/elasticity/TestIsotropicLinearElasticity2D_UniformStrain.cc
- tests/mmstests/elasticity/TestIsotropicLinearElasticity3D_BodyForce.cc
- tests/mmstests/elasticity/TestIsotropicLinearElasticity3D_Gravity.cc
- tests/mmstests/elasticity/TestIsotropicLinearElasticity3D_GravityRefState.cc
- tests/mmstests/elasticity/TestIsotropicLinearElasticity3D_UniformStrain.cc
- tests/mmstests/faults/TestFaultKin2D_RigidBlocksStatic.cc
- tests/mmstests/incompressibleelasticity/TestIsotropicLinearIncompElasticity2D_BodyForce.cc
- tests/mmstests/incompressibleelasticity/TestIsotropicLinearIncompElasticity2D_Gravity.cc
- tests/mmstests/incompressibleelasticity/TestIsotropicLinearIncompElasticity2D_UniformPressure.cc
- tests/mmstests/incompressibleelasticity/TestIsotropicLinearIncompElasticity2D_UniformShear.cc
> Implement pythia journal activation in C++ TestDriver using command line arguments

- libsrc/pylith/fekernels/IsotropicLinearPoroelasticity.cc
Modified jacobian term to account for three field formulation
> Modified Jf3uu poro residual (three field formulation)

- libsrc/pylith/bc/AbsorbingDampers.cc
- libsrc/pylith/bc/DirichletTimeDependent.cc
- libsrc/pylith/bc/NeumannTimeDependent.cc
- libsrc/pylith/faults/FaultCohesiveKin.cc
- libsrc/pylith/faults/KinSrc.cc
- libsrc/pylith/materials/Elasticity.cc
- libsrc/pylith/materials/IncompressibleElasticity.cc
- libsrc/pylith/materials/Poroelasticity.cc
- libsrc/pylith/meshio/OutputSolnPoints.cc
- libsrc/pylith/problems/TimeDependent.cc
- libsrc/pylith/testing/MMSTest.cc
- libsrc/pylith/testing/MMSTest.hh
- libsrc/pylith/topology/Field.cc
- libsrc/pylith/topology/Field.hh
- tests/libtests/bc/TestAbsorbingDampers.cc
- tests/libtests/bc/TestNeumannTimeDependent.cc
- tests/libtests/feassemble/TestAuxiliaryFactory.cc
- tests/libtests/meshio/TestOutputSolnPoints.cc
* Fix Field copy constructor (copy discretization and create local vector).
* Remove superfluous calls to `Field::zeroLocal()` (`allocate()` zeros the vector).
* Clean up `MMSTest` (remove obsolete `_solutionDot`).
> Fix Field copy constructor

- examples/2d/bar_waves/pylithapp.cfg
- examples/2d/bar_waves/step01_pwave_reflected.cfg
- examples/2d/bar_waves/step02_swave_reflected.cfg
- examples/2d/bar_waves/step03_swave_absorbed.cfg
- examples/2d/bar_waves/step04_swave_prescribedslip.cfg
- libsrc/pylith/feassemble/IntegratorDomain.cc
- tests/fullscale/linearelasticity/faults-2d/twoblocks_soln.py
* Add missing metadata to `examples/2d/bar_waves`
* Small cleanup.
> Add missing metadata to examples/2d/bar_waves

- libsrc/pylith/Makefile.am
- libsrc/pylith/problems/GreensFns.cc
- libsrc/pylith/problems/GreensFns.hh
- libsrc/pylith/problems/Makefile.am
- libsrc/pylith/problems/ProgressMonitorStep.cc
- libsrc/pylith/problems/ProgressMonitorStep.hh
- libsrc/pylith/problems/problemsfwd.hh
- modulesrc/problems/GreensFns.i
- modulesrc/problems/Makefile.am
- modulesrc/problems/problems.i
- pylith/problems/GreensFns.py
- pylith/problems/ProgressMonitorStep.py
Setup problem for Green's functions problem
> Greens fns problem setup

- pylith/apps/PetscApplication.py
- tests/mmstests/elasticity/Makefile.am
- tests/mmstests/faults/Makefile.am
- tests/mmstests/incompressibleelasticity/Makefile.am
Now that the PyLithApp has a facility array (problems), we need to deallocate all components in a facility array in PetscApplication.
> Add deallocation of facility arrays to PetscApplication

- docs-sphinx/developer/contributing/codingstyle.md
Updated grammatical errors in first line of codingstyle.md ('added conventions') and in object declaration files (added 'use')
> Updated grammatical errors in codingstyle.md

- docker/pylith-docenv
- docs-sphinx/conf.py
- docs-sphinx/index.md
- docs-sphinx/quickref.md
- docs-sphinx/references.bib
- docs-sphinx/references.md
- docs-sphinx/requirements.txt
* Configure Sphinx+MyST bibtex extension.
* Add references.bib with existing references.
* Add reference page at end.
* Create example citations in quickref.
> Use sphinx bibtex extension for references.

- configure.ac
- libsrc/pylith/bc/AbsorbingDampers.cc
- libsrc/pylith/bc/AbsorbingDampers.hh
- libsrc/pylith/bc/DirichletTimeDependent.cc
- libsrc/pylith/bc/DirichletTimeDependent.hh
- libsrc/pylith/bc/DirichletUserFn.cc
- libsrc/pylith/bc/DirichletUserFn.hh
- libsrc/pylith/bc/NeumannTimeDependent.cc
- libsrc/pylith/bc/NeumannTimeDependent.hh
- libsrc/pylith/bc/NeumannUserFn.cc
- libsrc/pylith/bc/NeumannUserFn.hh
- libsrc/pylith/faults/FaultCohesiveKin.cc
- libsrc/pylith/faults/FaultCohesiveKin.hh
- libsrc/pylith/materials/Material.cc
- libsrc/pylith/materials/Material.hh
- libsrc/pylith/problems/Physics.hh
- libsrc/pylith/problems/Problem.cc
- libsrc/pylith/testing/FaultCohesiveStub.cc
- libsrc/pylith/testing/FaultCohesiveStub.hh
- libsrc/pylith/testing/PhysicsStub.cc
- libsrc/pylith/testing/PhysicsStub.hh
- modulesrc/bc/AbsorbingDampers.i
- modulesrc/bc/DirichletTimeDependent.i
- modulesrc/bc/NeumannTimeDependent.i
- modulesrc/faults/FaultCohesiveKin.i
- modulesrc/materials/Material.i
- modulesrc/problems/Physics.i
- tests/mmstests/faults/TestFaultKin2D_ShearNoSlipStatic.cc
Adjusts createConstraint functions to return a vector of constraints (createConstraints)
> Multi constraints

- pylith/meshio/Xdmf.py
and then use that to determine whether decode() is needed.
> Changed _getXdmfVectorFieldType to check argument type,

- libsrc/pylith/bc/AbsorbingDampers.cc
- libsrc/pylith/bc/NeumannTimeDependent.cc
- libsrc/pylith/bc/NeumannUserFn.cc
- libsrc/pylith/faults/FaultCohesiveKin.cc
- libsrc/pylith/faults/KinSrc.cc
- libsrc/pylith/feassemble/ConstraintSpatialDB.cc
- libsrc/pylith/feassemble/FEKernelKey.hh
- libsrc/pylith/feassemble/FEKernelKey.icc
- libsrc/pylith/feassemble/Integrator.hh
- libsrc/pylith/feassemble/IntegratorBoundary.cc
- libsrc/pylith/feassemble/IntegratorBoundary.hh
- libsrc/pylith/feassemble/IntegratorDomain.cc
- libsrc/pylith/feassemble/IntegratorDomain.hh
- libsrc/pylith/feassemble/IntegratorInterface.cc
- libsrc/pylith/feassemble/IntegratorInterface.hh
- libsrc/pylith/materials/Elasticity.cc
- libsrc/pylith/materials/IncompressibleElasticity.cc
- libsrc/pylith/materials/Poroelasticity.cc
Combine ResidualPart and JacobianPart in Integrator into EquationPart.
There is no need to use separate part values for the residual and Jacobian.
Closes #389
> Update for adding equation part to DMSetAuxiliaryVec.

- libsrc/pylith/fekernels/IsotropicLinearMaxwell.cc
- libsrc/pylith/materials/IsotropicLinearMaxwell.cc
Small changes on in Maxwell viscoelastic.
> Fixed Jacobian trigger, removed debugging comments.

- libsrc/pylith/fekernels/IsotropicLinearGenMaxwell.cc
- libsrc/pylith/materials/IsotropicLinearGenMaxwell.cc
> Added Jacobian trigger + minor code cleanup.

- configure.ac
- libsrc/pylith/faults/FaultCohesive.cc
- libsrc/pylith/faults/TopologyOps.cc
- libsrc/pylith/faults/TopologyOps.hh
* Include fix for using label value for fault boundary
> Update to PETSc 3.17.1

- libsrc/pylith/bc/BoundaryCondition.cc
- libsrc/pylith/faults/TopologyOps.cc
- libsrc/pylith/meshio/MeshIO.cc
- libsrc/pylith/meshio/MeshIOPetsc.cc
- libsrc/pylith/meshio/OutputSolnBoundary.cc
- libsrc/pylith/problems/Problem.cc
- libsrc/pylith/testing/MMSTest.cc
- libsrc/pylith/topology/FieldOps.cc
- libsrc/pylith/topology/MeshOps.cc
- pylith/topology/Distributor.py
- pylith/topology/MeshImporter.py
- pylith/topology/RefineUniform.py
Also sets null space for displacement field.
I believe there is at least one bug related to running in parallel associated with output. It appears to be a mismatch in MPI communication patterns.
Closes #434
> Resolves several bugs related to running in parallel

- docs/user/install/index.md
* Update names of tarballs.
* Update information about macOS binary (now includes Python).
> Update install information

- docs/user/examples/reverse-2d/step02-gravity-refstate.md
- docs/user/examples/reverse-2d/step03-gravity-incompressible.md
- docs/user/examples/reverse-2d/step04-surfload.md
- docs/user/examples/reverse-2d/step05-onefault.md
- docs/user/examples/reverse-2d/step06-twofaults-elastic.md
- docs/user/examples/reverse-2d/step07-twofaults-maxwell.md
- docs/user/examples/reverse-2d/step08-twofaults-powerlaw.md
- examples/reverse-2d/pylithapp.cfg
- examples/reverse-2d/step02_gravity_refstate.cfg
- examples/reverse-2d/step03_gravity_incompressible.cfg
* FIX: Rename 'plate' to 'crust' to match documentation.
* DOCS: Fix sample output (show consistent environment).
> Clean up examples/reverse-2d

- applications/powerlaw_gendb
- pylith/bc/DirichletTimeDependent.py
- pylith/bc/NeumannTimeDependent.py
- pylith/utils/SimulationMetadata.py
Also include small fixes for configuration errors in `DirichletTimeDependent` and `NeumannTimeDependent`.
> Add check of PyLith version against constraints in simulation metadata.

- libsrc/pylith/fekernels/IsotropicLinearPoroelasticity.cc
- libsrc/pylith/fekernels/Poroelasticity.cc
- libsrc/pylith/utils/error.h
- libsrc/pylith/utils/error.hh
* Remove unused variables from poroelasticity kernels.
* Fix use of SETERRQ().
> Fix build warnings

- libsrc/pylith/feassemble/ConstraintSimple.cc
When we have a buried fault edge and need to impose a constraint on the Lagrange multiplier and are running in parallel, we can encounter the situation where a process has a degree of freedom that needs to be constrained for the buried edge but no cell. Because we use the cell to get the DS, we can't get the proper DS needed in the call to PetscDSAddBoundary(). The fix is to use the default DS, the correct field, but set the number of constrained components to 0 (Nc=0, comps=NULL) in the call to PetscDSAddBoundary(). This avoids the checks and is valgrind clean.
> FIX: Use zero constraints when we don't have a cell to get the DS for constraining buried edges in parallel

- developer/downloads.py
- developer/upload_release_asset.py
Also update downloads script to use requests Python module.
> Add Python script for uploading release assets for GitHub.

- libsrc/pylith/problems/GreensFns.cc
- libsrc/pylith/utils/PetscOptions.cc
- libsrc/pylith/utils/PetscOptions.hh
- modulesrc/utils/PetscOptions.i
- pylith/testing/FullTestApp.py
- pylith/utils/PetscDefaults.py
- tests/fullscale/cornercases/faults-2d/TestTwoBlocks.py
- tests/fullscale/linearelasticity/faults-2d/TestShearNoSlip.py
- tests/fullscale/linearelasticity/faults-2d/TestThreeBlocks.py
- tests/fullscale/linearelasticity/faults-3d/TestTwoBlocks.py
- tests/fullscale/poroelasticity/cryer/TestCryer.py
- tests/fullscale/poroelasticity/cryer/cryer.cfg
- tests/fullscale/poroelasticity/mandel/TestMandel.py
- tests/fullscale/poroelasticity/mandel/mandel.cfg
- tests/fullscale/poroelasticity/terzaghi/TestTerzaghi.py
- tests/fullscale/poroelasticity/terzaghi/terzaghi.cfg
> Update PETSc options to include using POD for initial guess.

- .vscode/settings.json
- libsrc/pylith/bc/DirichletTimeDependent.cc
- libsrc/pylith/bc/TimeDependentAuxiliaryFactory.cc
- libsrc/pylith/faults/FaultCohesive.cc
- libsrc/pylith/faults/KinSrc.cc
- libsrc/pylith/faults/KinSrcConstRate.cc
- libsrc/pylith/faults/KinSrcConstRate.hh
- libsrc/pylith/fekernels/BoundaryDirections.hh
- libsrc/pylith/fekernels/NeumannTimeDependent.hh
- libsrc/pylith/fekernels/TimeDependentFn.hh
Create functions for each term in time-dependent function. Allow reuse across Dirichlet and Neumann BC.
> Refactor time-dependent function implementation.

- libsrc/pylith/topology/Field.cc
- libsrc/pylith/topology/Field.hh
> Use custom layout for viewing field to facilitate debugging.

- libsrc/pylith/topology/Field.cc
- tests/fullscale/linearelasticity/faults-2d/TestShearNoSlip.py
- tests/fullscale/linearelasticity/faults-2d/TestThreeBlocks.py
- tests/fullscale/linearelasticity/faults-2d/meshes.py
- tests/fullscale/linearelasticity/faults-2d/pylithapp.cfg
- tests/fullscale/linearelasticity/faults-2d/shearnoslip_soln.py
- tests/fullscale/linearelasticity/faults-2d/threeblocks_soln.py
- tests/fullscale/linearelasticity/faults-3d/TestTwoBlocks.py
- tests/fullscale/linearelasticity/faults-3d/meshes.py
- tests/fullscale/linearelasticity/faults-3d/twoblocks.cfg
- tests/fullscale/linearelasticity/faults-3d/twoblocks_soln.py
Fix bugs related to output of fault solution fields, such as the Lagrange multiplier field.
> Fix output of fault fields (Lagrange multiplier)

- libsrc/pylith/fekernels/IsotropicLinearPoroelasticity.hh
I deleted two lines of commented code that had been previously missed.
> Deleted commented code

- docs/user/governingeqns/poroelasticity/index.md
Updated the definition of Biot Modulus in the documentations.
> Doc: updated Biot Modulus definition.

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/debugging-help.md
- .github/ISSUE_TEMPLATE/feature-request.md
> DOCS: Update GitHub issue templates.

- pylith/faults/KinSrcTimeHistory.py
- tests/fullscale/linearelasticity/faults-2d/Makefile.am
- tests/fullscale/linearelasticity/faults-2d/shearnoslip.cfg
- tests/fullscale/linearelasticity/faults-2d/zeroslipfn.timedb
Fix errors in KinSrcTimeHistory Python object
Closes #641
> FIx errors associated with using KinSrcTimeHistory

- libsrc/pylith/meshio/MeshIOPetsc.cc
> FIX: Rewrite MeshIOPetsc::_fixMaterialLabel() to remove bottleneck.

- libsrc/pylith/topology/RefineUniform.cc
> FIX: Fix ordering of points after refinement (use DMPlexReorderCohesiveSupports()).

- docs/_templates/sidebar-cig.html
- docs/user/install/index.md
- docs/user/run-pylith/overview.md
- examples/reverse-2d/step06_twofaults_elastic.cfg
- release-notes/checklist.txt
> Fix typo in code box for how to run pylith after installation + a couple other typo fixes

- CHANGES.md
- CITATION.cff
- README.md
- configure.ac
- docs/conf.py
- docs/intro/preface.md
- docs/user/install/index.md
- libsrc/pylith/faults/TopologyOps.cc
- release-notes/Makefile.am
- release-notes/announce_v4.1.2.md
- setup.cfg
> Fix cohesive cells orientation

- docs/user/install/index.md
> DOCS: Add instructions for setup of WSL with GUI apps (Gmsh and PyVista)

- docs/user/install/index.md
> DOCS: Add instructions for running setup.sh with WSL related arguments.

- examples/strikeslip-2d/step05_greensfns.cfg
- examples/subduction-3d/step07a_leftlateral.cfg
- examples/subduction-3d/step07b_reverse.cfg
- libsrc/pylith/faults/FaultCohesive.cc
- libsrc/pylith/faults/FaultCohesive.hh
- libsrc/pylith/faults/FaultCohesiveImpulses.cc
- libsrc/pylith/faults/FaultCohesiveImpulses.hh
- libsrc/pylith/faults/FaultCohesiveKin.cc
- libsrc/pylith/faults/FaultCohesiveKin.hh
- modulesrc/faults/FaultCohesive.i
- modulesrc/faults/FaultCohesiveKin.i
- tests/fullscale/linearelasticity/greensfns-2d/pylithapp.cfg
> Add output of fault traction change for Green's functions

- CHANGES.md
- docs/user/components/bc/AuxSubfieldsTimeDependent.md
- docs/user/components/materials/AuxSubfieldsIsotropicLinearPoroelasticity.md
- docs/user/components/materials/DerivedSubfieldsPoroelasticity.md
- docs/user/components/materials/index.md
- docs/user/components/problems/InitialConditionPatch.md
- docs/user/components/problems/SolnDispLagrange.md
- docs/user/components/problems/SolnDispPresTracStrainLagrange.md
- docs/user/components/problems/SolnDispPresTracStrainVelPdotTdotLagrange.md
- docs/user/components/problems/SolnDispVelLagrange.md
- docs/user/components/problems/SubfieldLagrangeFault.md
- docs/user/components/problems/index.md
- docs/user/components/topology/Distributor.md
- docs/user/components/utils/PetscDefaults.md
- docs/user/run-pylith/petsc-options.md
- libsrc/pylith/utils/PetscOptions.cc
- libsrc/pylith/utils/PetscOptions.hh
- modulesrc/utils/PetscOptions.i
- pylith/utils/PetscDefaults.py
* Updates component information in user guide (sync with code).
Closes #753
> Turn on collective PETSc HDF5 output by default (resolves HDF5 1.14 errors with NFS)

- CHANGES.md
- configure.ac
- docs/user/run-pylith/troubleshooting.md
> DOCS: Add section on troubleshooting solver issues

- .github/workflows/ci-main.yml
- .github/workflows/ci-stage-1.yml
- .github/workflows/ci-stage-2.yml
- docker/pylith-docenv
>  Create CI pipeline using GitHub Actions

- pylith/meshio/DataWriter.py
- pylith/meshio/DataWriterHDF5.py
- pylith/meshio/DataWriterHDF5Ext.py
- pylith/meshio/DataWriterVTK.py
- pylith/problems/ProgressMonitor.py
- pylith/utils/DumpParameters.py
- tests/pytests/meshio/TestDataWriter.py
> FIX: Use pathlib instead of os for managing filesystem paths.
